### ISSUE TITLE
Quests?

### ISSUE THREAD

**Issue by ConfusedCrafter** [Tuga4Life/TTA-TripToAvaritia#1]
i just loaded into a vanilla overworld with a bag and no quests, im a little confused. is this intentional?

**Comment by Tuga4Life** [comment]
Sorry for the delay. At the time I thought I would be able to complete the quest book in 2 days, that's why I hadn't put the modpack in Alpha, but it ended up taking longer.
Trip To Avaritia was recently updated with lots of new mods and the quest book, check it out.
