### ISSUE TITLE
im stuck in a screen and idk how to get out of it

### ISSUE THREAD

**Issue by Serpent025** [Tuga4Life/TTA-TripToAvaritia#2]
I cant really say much about it its what the title said but ii can send some screenshots i will ry to relaucnh it to see that worked
![Uploading image_2024-09-03_151750159.png…]()

**Comment by Tuga4Life** [comment]
I can't see the image. Did you attach the image?

**Comment by Serpent025** [comment]
![Screenshot 2024-09-03 151721](https://github.com/user-attachments/assets/cc901846-4957-4647-babd-9e84d5980a15)
okay here is the image i think

**Comment by Tuga4Life** [comment]
that was a problem that is fixed in the newest versions
you just need to update the modpack, dowload the file TripToAvaritia_v1.3.2 is the newest version

**Comment by Serpent025** [comment]
oh ok ty

**Comment by Tuga4Life** [comment]
no problem, have fun

**Comment by Serpent025** [comment]
oh ok thx
